### ISSUE TITLE
Add solution for hackerrank problem- Drawing Book

### ISSUE THREAD

**Issue by nishant-sethi** [nishant-sethi/HackerRank#4]
Go to the following link to see the problem statement and add the solution in appropriate folder
https://www.hackerrank.com/challenges/drawing-book/problem

**Comment by anjali1102** [comment]
[drawingBook.txt](https://github.com/nishant-sethi/HackerRank/files/5290330/drawingBook.txt)

**Comment by anjali1102** [comment]
added c++ implementation of drawing book

**Comment by nishant-sethi** [comment]
Thanks for your contribution. However, .txt file won't really help. Is it possible for you to add the file in appropriate folder of repository with proper extension (.cpp, .c, .java).
