### ISSUE TITLE
Add solution to hackerrank problem-Save the Prisoner!

### ISSUE THREAD

**Issue by nishant-sethi** [nishant-sethi/HackerRank#5]
Go the following link to see the problem statement and add solution into the appropriate folder.
https://www.hackerrank.com/challenges/save-the-prisoner/problem

**Comment by rsethi3950** [comment]
can i take up this issue?

**Comment by nishant-sethi** [comment]
@rsethi3950 go ahead!

**Comment by nishant-sethi** [comment]
@rsethi3950 code merged. good work :)
