### ISSUE TITLE
Add solution to the hackerrank problem- Circular Array Rotation

### ISSUE THREAD

**Issue by nishant-sethi** [nishant-sethi/HackerRank#6]
Go to the following link to see the problem statement and please add the solution into the appropriate folder.
https://www.hackerrank.com/challenges/circular-array-rotation/problem

**Comment by rsethi3950** [comment]
is the issue open?

**Comment by nishant-sethi** [comment]
@rsethi3950 yes!

**Comment by shubham2704** [comment]
is the issue Still open?

**Comment by nishant-sethi** [comment]
@shubham2704 yes

**Comment by nishant-sethi** [comment]
Issue closed
