### ISSUE TITLE
Add solution to the hackerrank problem - Equalize the Array

### ISSUE THREAD

**Issue by nishant-sethi** [nishant-sethi/HackerRank#7]
Go to the following link to see the problem statement and add the solution into the appropriate folder.
https://www.hackerrank.com/challenges/equality-in-a-array/problem

**Comment by anjali1102** [comment]
`#include<bits/stdc++.h>
using namespace std;
int main() {
    int n;cin>>n;
    int a[n];
    for(int i=0;i<n;i++)
        cin>>a[i];
    //after sorting, check for adjacent elements 
    sort(a,a+n);
    //consider first element as max ,iterate from
    //2 element to the end , if found max equal to arr[i]
    //increase c and update maxi with c

    int max=a[0];
    int c=1,maxi=1;
    for(int i=1;i<n;i++){
        if(a[i]==max){
            c++;
            if(c>maxi){
                maxi=c;
            }
        }
        else{
            max=a[i];
            c=1;
        }        
    }
    cout<<n-maxi<<endl;
    return 0;
}



`

**Comment by anjali1102** [comment]
added c++ implementation of Equalize the array

**Comment by anjali1102** [comment]
added c++ implementation of Equalize the array

**Comment by anjali1102** [comment]
[equalizeArray.txt](https://github.com/nishant-sethi/HackerRank/files/5290269/equalizeArray.txt)

**Comment by nishant-sethi** [comment]
Thanks for your contribution. However, the .txt file won't really help. Is it possible for you to add the file in the appropriate folder of the repository with the proper extension (.cpp, .c, .java)?
