### ISSUE TITLE
Add solution to hackerrank problem-ACM ICPC Team!

### ISSUE THREAD

**Issue by nishant-sethi** [nishant-sethi/HackerRank#8]
Go the following link to see the problem statement and add solution into the appropriate folder.
https://www.hackerrank.com/challenges/acm-icpc-team/problem

**Comment by anjali1102** [comment]
[acm_icpc.txt](https://github.com/nishant-sethi/HackerRank/files/5290295/acm_icpc.txt)

**Comment by anjali1102** [comment]
added c++ implementation of acm icpc team

**Comment by nishant-sethi** [comment]
Thanks for your contribution. However, .txt file won't really help. Is it possible for you to add the file in appropriate folder of repository with proper extension (.cpp, .c, .java).

**Comment by anjali1102** [comment]
[acm_icpc.cpp](https://github.com/nishant-sethi/HackerRank/files/5299891/acm_icpc.cpp)
